#ifndef _AUDIO_TIMING_HPP
#define _AUDIO_TIMING_HPP

#include "core/timing.hpp"

#define OUTPUT_SAMPLE_FREQUENCY 49152
#define FRAME_SEQUENCER_FREQUENCY 512

#define OUTPUT_SAMPLE_PERIOD (CLOCK_FREQUENCY / OUTPUT_SAMPLE_FREQUENCY)
#define FRAME_SEQUENCER_PERIOD (CLOCK_FREQUENCY / FRAME_SEQUENCER_FREQUENCY)

#define OUTPUT_BUFFER_SAMPLES 1024

#endif
